### PR TITLE
use pnpm

### PR DESCRIPTION
**Pull request by oxSaturn**
Closes https://github.com/Velocimeter/frontend/issues/232 and closes https://github.com/Velocimeter/frontend/issues/219

---

## PR-Codex overview

> The following files were skipped due to too many changes: `Frontend-v1-Original/pnpm-lock.yaml`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by t0rbik** [comment]
Screenshot 2023-07-09 at 1 27 49 pm
maybe add engine version to package.json

**Comment by oxSaturn** [comment]
> Screenshot 2023-07-09 at 1 27 49 pm maybe add engine version to package.json

Already included,

CleanShot-w0uUkBSu@2x

 Chances are it's complaining that I'm using `>=18` syntax which mean it will use Node.js 19 when available.

**Comment by t0rbik** [comment]
can we set node to 18?

**Comment by t0rbik** [comment]
awesome

**Pull request merged**
