### PR TITLE
refactor Votes to fix bugs

### PR DESCRIPTION
**Pull request by oxSaturn**
There're at least two bugs in this `vote` page as I found when voting last epoch.

1. Voted nft still stays under `Available to Vote this Epoch` after you casted the vote, which means you'll have to refresh the page after vote. And it was introduced in https://github.com/Velocimeter/frontend/pull/81
2. Say you have multiple nfts, and you select one other than the default one when page is still loading other things, the selected nft will revert to the default one, and this is sort of annoying.

In this pull request:

1. I've refactor the `useState` to `useReducer`, which I believe is easier to reason about when there're many states
2. I've separated different logics into different `useEffect`, i.e., do one thing in one `useEffect` instead of keeping them all in one `useEffect` which could easily result in unnecessary rerenders.

---

## PR-Codex overview
This PR adds state management using `useReducer` to the `ssVotes` component, replaces `useState` with `dispatch` function calls, and adds several `useEffect` hooks to handle component state updates. 

### Detailed summary
- Replaces `useState` with `useReducer` for state management.
- Adds an `ACTION` type and a `reducer` function to handle state updates.
- Adds several `useEffect` hooks to handle component state updates, such as setting `veToken`, fetching `gauges`, `vestNFTs`, and `votes` data, and handling warnings and vote results.
- Replaces `useState` calls with `dispatch` function calls to update component state.
- Handles changes to the selected `VestNFT` using `handleChange` function and `setToken` action.
- Handles changes to the search input using `onSearchChanged` function and `setSearch` action.

> The following files were skipped due to too many changes: `Frontend-v1-Original/components/ssVotes/ssVotes.tsx`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by oxSaturn** [comment]
@t0rbik I see you're working on https://github.com/Velocimeter/frontend/pull/89, so if you already fixed the bugs mentioned above, feel free to close this, as merging this one into your pr might take a lot of work from what I can tell.

**Comment by t0rbik** [comment]
I will look into it and think about. Not sure how soon #89 will be ready.

**Comment by t0rbik** [comment]
Screenshot 2023-05-24 at 1 03 28 pm

By glance code looks ok. However in preview i get stuck on this state. Nfts does not show up, neither do pairs to vote on

**Comment by oxSaturn** [comment]
> Screenshot 2023-05-24 at 1 03 28 pm
> By glance code looks ok. However in preview i get stuck on this state. Nfts does not show up, neither do pairs to vote on. When I reload the page, everything works as expected. But when I go to another tab and back to vote = stuck again.

yeah, it's a bug where the state gets initialized again and those events we were listening won't run another time.

**Comment by oxSaturn** [comment]
Sort of messy to manage states with dependencies like this, wondering if `react-query` will improve it.

**Comment by oxSaturn** [comment]
> Regarding this... I got to point in #89 with this issue fixed. Although still need to migrate many actions from flux there. needs time. Commit [b78bd5e](https://github.com/Velocimeter/frontend/commit/b78bd5eedd08131b4bfd71d301dfa9382b7883c2)

That's great, I can wait, lol, and so far I didn't find anyone complaining about it. Guess they can just refresh the page.

**Comment by t0rbik** [comment]
in favour of #89

**Pull request closed without merging**
